services:
  - type: web
    name: mastering-dsa-python
    env: node
    plan: free
    buildCommand: npm run render-build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://amanrajsathishkumar05_db_user:Amanraj_2005@dsa-competition.qsecs3c.mongodb.net/?appName=DSA-Competition
      - key: JWT_SECRET
        value: super_secret_dsa_competition_key_2026_sathyabama
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        value: adminpassword123
